"use client";

import { useState, useEffect } from "react";
import type { MarketData } from "@/app/types";
import { CN_TICKERS } from "@/app/lib/fallbackData";
import PriceCard from "./PriceCard";

export default function CNScanner() {
  const [cnData, setCnData] = useState<MarketData[]>(CN_TICKERS);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/prices?market=cn")
      .then((r) => r.json())
      .then((data) => {
        if (Array.isArray(data) && data.length > 0) setCnData(data);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-lg font-semibold text-gray-200">
          China A-Shares Scanner
        </h2>
        <p className="text-xs text-gray-500 mt-1">
          Multi-factor scoring: technicals, fundamentals, and sentiment
        </p>
      </div>

      {/* A-share price cards — real-time via Sina API */}
      <div>
        <h3 className="text-sm font-semibold text-gray-400 mb-3">
          Watchlist
        </h3>
        {loading ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {[1, 2, 3].map((i) => (
              <div
                key={i}
                className="rounded border border-gray-800/60 bg-[#13131a] px-3 py-2.5 animate-pulse h-24"
              />
            ))}
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {cnData.slice(0, 3).map((m) => (
              <PriceCard key={m.asset} data={m} />
            ))}
          </div>
        )}
      </div>

      {/* Scanner empty state — honest about no backend */}
      <div className="rounded border border-gray-800/50 bg-[#13131a] p-8 text-center">
        <div className="max-w-md mx-auto space-y-4">
          <div className="w-12 h-12 mx-auto rounded-full bg-gray-800/60 border border-gray-700/50 flex items-center justify-center">
            <svg
              className="w-6 h-6 text-gray-500"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z"
              />
            </svg>
          </div>

          <div>
            <h3 className="text-sm font-semibold text-gray-300">
              No Scan Results Available
            </h3>
            <p className="text-xs text-gray-500 mt-1.5 leading-relaxed">
              Scanner results are generated by the FinClaw CLI. Run a scan to
              populate this view with real multi-factor signals.
            </p>
          </div>

          <div className="bg-gray-900/60 border border-gray-700/40 rounded-md p-4 text-left">
            <p className="text-[10px] text-gray-500 uppercase tracking-wider mb-2 font-semibold">
              Get Started
            </p>
            <code className="text-xs text-teal-400 font-mono block leading-relaxed">
              $ finclaw scan --universe a-shares --output json
            </code>
            <p className="text-[10px] text-gray-600 mt-2">
              Then import results via the API or{" "}
              <span className="text-gray-400">finclaw.config.ts</span>.
            </p>
          </div>

          <a
            href="https://github.com/NeuZhou/finclaw"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-block text-xs text-slate-400 hover:text-slate-300 transition-colors"
          >
            Learn more in the documentation →
          </a>
        </div>
      </div>

      <div className="p-3 bg-gray-800/20 border border-gray-700/30 rounded text-xs text-gray-500">
        <span className="text-gray-600">
          Note: A-share color convention follows China market standard (red = up,
          green = down)
        </span>
      </div>
    </div>
  );
}
