#!/usr/bin/env python3
"""
AI-Generated Strategy Example — FinClaw
========================================
This strategy was generated by FinClaw's AI Strategy Generator.
It demonstrates what `finclaw generate-strategy` produces.

Strategy: Mean reversion with Bollinger Band squeeze detection.
- Buy when price touches lower band AND band width is contracting (squeeze)
- Sell when price reaches middle band or 5% stop loss

Usage:
    python examples/ai_generated.py
    # Generate your own:
    finclaw generate-strategy "mean reversion on Bollinger Bands with squeeze detection"
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np


def fetch(ticker: str = "AAPL", period: str = "2y"):
    import yfinance as yf
    import warnings, logging
    logging.getLogger("yfinance").setLevel(logging.CRITICAL)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return yf.Ticker(ticker).history(period=period)


def bollinger(close, period=20, num_std=2.0):
    """Compute Bollinger Bands."""
    sma = np.full_like(close, np.nan)
    upper = np.full_like(close, np.nan)
    lower = np.full_like(close, np.nan)
    width = np.full_like(close, np.nan)

    for i in range(period - 1, len(close)):
        window = close[i - period + 1 : i + 1]
        m = np.mean(window)
        s = np.std(window)
        sma[i] = m
        upper[i] = m + num_std * s
        lower[i] = m - num_std * s
        width[i] = (upper[i] - lower[i]) / m if m > 0 else 0

    return sma, upper, lower, width


def run(ticker="AAPL", period="2y", capital=100_000):
    df = fetch(ticker, period)
    if df is None or len(df) < 30:
        print(f"Not enough data for {ticker}")
        return

    close = np.array(df["Close"].tolist(), dtype=np.float64)
    mid, upper, lower, width = bollinger(close, 20, 2.0)

    # Detect squeeze: band width in bottom 25th percentile of recent 50 bars
    position = 0
    entry_price = 0
    cash = capital
    stop_loss_pct = 0.05
    trades = []
    wins = 0

    for i in range(50, len(close)):
        recent_widths = width[i - 50 : i]
        valid = recent_widths[~np.isnan(recent_widths)]
        if len(valid) == 0:
            continue
        squeeze_threshold = np.percentile(valid, 25)
        is_squeeze = width[i] <= squeeze_threshold

        if position == 0:
            # Buy: price at/below lower band during squeeze
            if close[i] <= lower[i] and is_squeeze:
                shares = int(cash / close[i])
                if shares > 0:
                    position = shares
                    entry_price = close[i]
                    cash -= shares * close[i]
                    trades.append(("BUY", i, close[i]))
        else:
            # Exit: price reaches mid band (take profit) or stop loss
            hit_target = close[i] >= mid[i]
            hit_stop = close[i] <= entry_price * (1 - stop_loss_pct)
            if hit_target or hit_stop:
                cash += position * close[i]
                pnl = close[i] - entry_price
                if pnl > 0:
                    wins += 1
                trades.append(("SELL", i, close[i], "TP" if hit_target else "SL"))
                position = 0

    portfolio = cash + position * close[-1]
    ret = portfolio / capital - 1
    bh = close[-1] / close[0] - 1
    sell_count = sum(1 for t in trades if t[0] == "SELL")
    win_rate = wins / sell_count if sell_count > 0 else 0

    print(f"\n  🤖 AI-Generated Strategy: BB Squeeze Mean Reversion")
    print(f"  Ticker: {ticker} | Period: {period}")
    print(f"  Logic:  Buy at lower band during squeeze → TP at mid band | SL 5%")
    print(f"  Return: {ret:+.1%}  |  Buy&Hold: {bh:+.1%}  |  Alpha: {ret - bh:+.1%}")
    print(f"  Trades: {len(trades)}  |  Win Rate: {win_rate:.0%}")
    print(f"  Final:  ${portfolio:,.0f}\n")
    print(f"  💡 Generate your own: finclaw generate-strategy \"your idea here\"")
    print()


if __name__ == "__main__":
    ticker = sys.argv[1] if len(sys.argv) > 1 else "AAPL"
    run(ticker)
